data:
  raw_data_path: "data/raw/"
  processed_data_path: "data/processed/"
  test_samples_path: "data/test_samples/"
  sample_rate: 16000
  n_mfcc: 13
  max_audio_duration: 10.0

model:
  acoustic_model_path: "models/acoustic_model.h5"
  language_model_path: "models/language_model.h5"
  batch_size: 32
  epochs: 50
  learning_rate: 0.001

training:
  train_data_split: 0.8
  validation_data_split: 0.1
  test_data_split: 0.1

evaluation:
  wer_threshold: 0.2

output:
  results_path: "output/results/"
